### ISSUE TITLE
protect master branch

### ISSUE THREAD

**Issue by michaelfeil** [johannespischinger/senti_anal#17]
Disable in settings that we can commit to master branch

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

After that we might should enable auto-merging after pipeline completion /auto-merge:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request#enabling-auto-merge

**Comment by johannespischinger** [comment]
Branch protected with merge request approval

**Comment by johannespischinger** [comment]
Auto-merging still required to adjust

**Comment by johannespischinger** [comment]
Auto-merge enabled
