### ISSUE TITLE
add github secrets token

### ISSUE THREAD

**Issue by michaelfeil** [johannespischinger/senti_anal#27]
https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/GitHub-Actions-Secrets-Example-Token-Tutorial

build-docs-ghpages.yaml
    # - name: Push changes to github repo/gh-pages
    #   uses: ad-m/github-push-action@master
    #   with:
    #     branch: gh-pages
    #     directory: gh-pages
    #     github_token: ${{ secrets.GITHUB_TOKEN }}

**Comment by michaelfeil** [comment]
Maybe need this setup for gcp too.

**Comment by johannespischinger** [comment]
Lines uncommented, token inserted SECRET_TOKEN
