### ISSUE TITLE
amazon_polarity doesn't contain any data file

### ISSUE THREAD

**Issue by michaelfeil** [johannespischinger/senti_anal#50]
`E           FileNotFoundError: The directory at amazon_polarity doesn't contain any data file

../anaconda3/envs/py39senti/lib/python3.9/site-packages/datasets/data_files.py:295: FileNotFoundError
=================================================================== short test summary info ===================================================================
FAILED tests/data/test_make_dataset.py::TestMakeDataset::test_make_dataset - FileNotFoundError: The directory at amazon_polarity doesn't contain any data file`

`coverage run -m pytest tests -m "not long" `

**Comment by max-27** [comment]
die Daten kann man nicht direkt aus dem amazon polarity ziehen nur aus dem processed folder 
für den Rest brauchst du die load function vom transformers Modul

**Comment by michaelfeil** [comment]
happens when the folder amazon_polarity/ .. exists, but is empty. 
I think the dvc v1.0 is not correctly configured?

**Comment by michaelfeil** [comment]
resolved with new dvc config
