### ISSUE TITLE
hydra model train fails due to relative path

### ISSUE THREAD

**Issue by michaelfeil** [johannespischinger/senti_anal#56]
```
self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '../../models'
(py39senti) michi@lenovo-michi:~/senti_anal$ 
```
fails,
but

`(py39senti) michi@lenovo-michi:~/senti_anal/opensentiment/models$ python train_model.py `
works. 

Proposal: We should not overwrite the `hydra: dir: path ` setting, and leave it to hydra instead

**Comment by max-27** [comment]
This is strange because for this works perfectly fine (on a Mac OS). I will research on the behaviour of the working directory of hydra

**Comment by michaelfeil** [comment]
resolved with new config
